name: Living Benefits
favicon: null
layout_spectrum: 0.35238
typography_spectrum: 0.59599
title: Be a HERO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a497d'
    - '#00254f'
    - '#000723'
    - '#cccccc'
    - '#305986'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
